title: "Kasimir Dederichs"
author: "Kasimir Dederichs"
description: "© 2022 - Kasimir Dederichs, powered by the contrast theme on Jekyll (nicklasbuschmann)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.html"}
  - {title: "News", file: "news.md"}
  - {title: "Publications", file: "publications.md"}
  - {title: "Teaching", file: "teaching.md"}
  - {title: "CV", file: "cv.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:kasimir.dederichs@nuffield.ox.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/kasimirdederichs"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Kasimir_D"}
  - {title: Bluesky, icon: twitter, url: "https://bsky.app/profile/kasimirdederichs.bsky.social"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
# - jekyll-feed
